### PR TITLE
Project reorganization. Addition of additional targets and schemes for iOS

### PR DESCRIPTION
**Pull request by Revolucent**
Changes in this pull request:

- Renamed the existing `Yaml` target to `Yaml OSX`, but kept its product name as `Yaml.framework`. Renamed its scheme to `Yaml OSX`.
- Added an iOS target (`Yaml iOS`), product (`Yaml.framework`) and scheme (`Yaml iOS`). Shared this scheme.
- Reorganized the on-disk structure to better reflect standard Xcode project organization, e.g., `src` -> `Yaml` and `test` -> `YamlTests`. Deleted the `src` and `test` folders.
- Deleted and ignored the `project.xcworkspace` file inside of the `Yaml.xcodeproj`. (No need to check this in.)
- Added `xcuserdata` to `.gitignore`.
- Deleted the Cartfile since it was empty and shouldn't be checked in anyway.
- Verified that the all of the tests work in both schemes.

### CODE REVIEW

**Comment by Revolucent** [comment]
And a bit more:

- Made Yaml.h public in the iOS project.
- Fixed a compiler warning in Regex.swift

**Comment by behrang** [comment]
That's really great. Thanks.

**Comment by Revolucent** [comment]
No problem! Yaml.swift has been a big help to me. Great work. :)

**Comment by behrang** [comment]
Thank you. Happy to hear that it is useful.

**Comment by Revolucent** [comment]
If you do any work with Core Data in Swift, check out my [Core Data Query Interface](https://github.com/Prosumma/CoreDataQueryInterface) library. Perhaps you'll find it useful.

**Pull request merged**
